### ISSUE TITLE
Won't connect to deluge

### ISSUE THREAD

**Issue by Redsandro** [cpoppema/docker-flexget#18]
I have a deluge container, running fine, ports exposed.

Config

```
    deluge:
      port: 58846
      path: /data/incoming/
      movedone: '/data/complete/'
      main_file_only: yes
```

However, none of the downloaded torrents can be added to deluge. Docker-flexget log:

```
2017-10-23 16:41 ERROR    deluge        test        Unable to use default config directory, exiting... ([Errno 13] Permission denied: '/home/abc')
```

**Comment by cpoppema** [comment]
Thanks for bringing this up @Redsandro. I don't use deluge myself, so it took some time figuring it out.

Flexget and Deluge operate separately, they do not have access to each others files. For this to work two things are required:

1. Create a user that flexget can use to connect with deluge.

Deluge has a file `auth` in its configuration directory. Open this and add a new line with just a username and password. If you save the file, it looks similar to this:

```
localclient:85d1134a573d8094e6ba6e97ae5fe41a1cf8122c:10
flexget:delugepassword
```

2. Add the machine and user + password to flexget's configuration. Since flexget connecting to deluge will be seen as a remote connection, you need to use all of these four options in `config.yml`:

```
    deluge:
      host: 192.168.1.213
      port: 58846
      username: flexget
      password: delugepassword
```

You might need to restart deluge to allow connections from new users, but this should do the trick.
