### ISSUE TITLE
IOError: Config `/config/config.yml` does not appear to be a file.

### ISSUE THREAD

**Issue by kquinsland** [cpoppema/docker-flexget#29]
Hey there!  Just want to start by saying thanks for putting the image together!

However, I am running into a problem; python can't seem to find my config file!

Here's the container that i started:

```
docker create --name=flexget --network media_net -e PGID=997 -e PUID=998 -e WEB_PASSWD=<omitted> -e TORRENT_PLUGIN=transmission -e FLEXGET_LOG_LEVEL=debug -p 5050:5050 -v /opt/flexget/config:/config -v /opt/transmission/downloads/torrent_files:/downloads cpoppema/docker-flexget
```

And when i run the container, i see the pip install work w/o issue.  It looks like once flexget tries to start there is an issue:

```
# docker container start flexget && docker logs -f flexget
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    998
User gid:    997
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-update-flexget: executing...
<omitted>
[cont-init.d] 20-update-flexget: exited 0.
[cont-init.d] 21-update-transmission: executing...
<omitted>
[cont-init.d] 21-update-transmission: exited 0.
[cont-init.d] 22-update-deluge: executing...
[cont-init.d] 22-update-deluge: exited 0.
[cont-init.d] 30-set-web-passwd: executing...
[cont-init.d] 30-set-web-passwd: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 24, in main
    manager = Manager(args)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 158, in __init__
    self.find_config(create=False)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 539, in find_config
    raise IOError('Config `%s` does not appear to be a file.' % config)
IOError: Config `/config/config.yml` does not appear to be a file.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 24, in main
    manager = Manager(args)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 158, in __init__
    self.find_config(create=False)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 539, in find_config
    raise IOError('Config `%s` does not appear to be a file.' % config)

<stack trace keeps repeating...>
```

Looking at `/usr/lib/python2.7/site-packages/flexget/manager.py:539` i see:

```
if not os.path.isfile(config):
            raise IOError('Config `%s` does not appear to be a file.' % config)
```

and from the exception, i know that `config` is set to `/config/config.yaml` which is valid:

```
root@2e9cdc9c9e16:/$ stat /config/config.yaml
  File: /config/config.yaml
  Size: 181       	Blocks: 8          IO Block: 4096   regular file
Device: 802h/2050d	Inode: 5119924     Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (  998/     abc)   Gid: (  997/     abc)
Access: 2018-05-27 21:45:37.803416351 +0000
Modify: 2018-05-27 21:45:44.575309242 +0000
Change: 2018-05-27 21:45:44.575309242 +0000
 Birth: -
root@2e9cdc9c9e16:/$ id -u abc
998
root@2e9cdc9c9e16:/$ id -g abc
997
root@2e9cdc9c9e16:/$ cat config/config.yaml
web_server: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 1

tasks:
  test task:
    rss: http://myfavoritersssite.com/myfeed.rss
    series:
      - My Favorite Show
```

Do you have any thoughts about what might be going wrong?  It is not clear to me why Python thinks that there is no file present when there clearly is a config file present.
