### ISSUE TITLE
`deluge-client` is missing

### ISSUE THREAD

**Issue by Oshayr** [cpoppema/docker-flexget#35]
Running latest:

```
Flexget       | 2018-10-19 22:02 DEBUG    deluge        ttv-rss         Error importing deluge-client: No module named deluge_client
Flexget       | 2018-10-19 22:02 CRITICAL task          ttv-rss         Plugin `deluge` cannot be used because dependency `deluge-client` is missing.
Flexget       | 2018-10-19 22:02 DEBUG    task          ttv-rss         deluge-client >=1.5 is required. `pip install deluge-client` to install.
Flexget       | 2018-10-19 22:02 WARNING  task          ttv-rss         Aborting task (plugin: deluge)
Flexget       | 2018-10-19 22:02 DEBUG    task_queue                    task ttv-rss aborted: TaskAbort(reason=Plugin `deluge` cannot be used because dependency `deluge-client` is missing., silent=False)
```

```
  Flexget: 
    environment: 
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "WEB_PASSWD=${WEB_PASSWD}"
      - TORRENT_PLUGIN=deluge
      - "TZ=${TZ}"
    image: cpoppema/docker-flexget
    ports: 
      - "5050:5050"
    restart: unless-stopped
    volumes: 
...
```
