### ISSUE TITLE
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied

### ISSUE THREAD

**Issue by wbern** [cpoppema/docker-flexget#66]
Any idea how to solve this problem?

```
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

This is my docker-compose.yml
```
version: '3'
services:
  flexget-irc-daemon:
    #build: ./images/flexget
    container_name: flexget-irc-daemon
    image: cpoppema/docker-flexget
    ports:
     - 5000:5000
    volumes:
      - ./volumes/flexget-irc-daemon:/etc/flexget
    restart: unless-stopped
    depends_on:
      - flexget-scanner
    # user: 1001:1001 #have tried commenting this one out, and not. same problem.
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Amsterdam
      - FLEXGET_LOG_LEVEL=debug
  flexget-scanner:
    container_name: flexget-scanner
    # build: ./images/flexget
    image: cpoppema/docker-flexget
    restart: unless-stopped
    ports:
      - 3540:3540
    volumes:
      - ./volumes/flexget-scanner:/etc/flexget
    # user: 1001:1001 #have tried commenting this one out, and not. same problem.
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Amsterdam
      - FLEXGET_LOG_LEVEL=debug
  kodi-headless:
    container_name: kodi-headless
    image: lsioarmhf/kodi-headless
  #  build: ./images/kodi-headless
    restart: unless-stopped
    depends_on:
      - kodi-mariadb
    #user: 1001:1001
    volumes:
      - ./volumes/kodi-headless:/config/.kodi
      - /storage/usbshare1
      - /storage/usbshare2
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/Amsterdam
    ports:
      - 8080:8080
      - 9090:9090
      - 9777:9777/udp
  kodi-mariadb:
    container_name: kodi-mariadb
    image: jsurf/rpi-mariadb
    restart: unless-stopped
    user: 1001:1001
    environment:
      - PUID=1001
      - PGID=1001
      - MYSQL_ROOT_PASSWORD=[removed]
    ports:
      - 3306:3306
    volumes:
      - ./volumes/kodi-mariadb/mysql:/var/lib/mysql
```
