### ISSUE TITLE
How can i set http_proxy for docker-flexget ?

### ISSUE THREAD

**Issue by gth7754125** [cpoppema/docker-flexget#68]
I use docker-flexget on my computer and use VPN to control my network connection.
i try adding the proxy setting to the 'config.yml'  and bind the port for http_proxy on 'docker-compose.yml'.
However, the connection timeout, i don't know how to set a proxy for docker-flexget alone.

**Comment by cpoppema** [comment]
Hello @gth7754125. Are you talking about https://flexget.com/Plugins/proxy ? Did you read the small print ?
> NOTE: Not all communication will go through the proxy, only certain plugins have been refactored to use this. The rss and download plugins will both use this proxy.

Please share (parts of) your config.yml

**Comment by gth7754125** [comment]
```yaml
web_server:
  bind: 0.0.0.0
  port: 3539

schedules:
  - tasks: '*'
    interval:
      minutes: 1

tasks:
  anime:
    rss: https://mikanani.me/RSS/Bangumi?bangumiId=2053&subgroupid=203
    proxy: http://127.0.0.1:1087
    accept_all: no
    regexp:
      reject:
        - 480p
        - 720p
    all_series:
      quality: 1080p
    #download: /data
    qbittorrent:
      host: 127.0.0.1
      port: 9092
      username: [****]
      password: [****]
    
```
```
flexget | 2020-02-19 21:47:16 INFO scheduler Starting scheduler

flexget | 2020-02-19 21:47:16 CRITICAL plugin anime Unable to download the RSS for task anime (https://mikanani.me/RSS/Bangumi?bangumiId=2053&subgroupid=203): HTTPSConnectionPool(host='mikanani.me', port=443): Max retries exceeded with url: /RSS/Bangumi?bangumiId=2053&subgroupid=203 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1cb0fc8d30>: Failed to establish a new connection: [Errno 111] Connection refused')))

flexget | 2020-02-19 21:47:16 WARNING task anime Aborting task (plugin: rss)
```
